name: apppetid
description: "Red social inteligente para mascotas y sus dueños."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase - Últimas versiones
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  firebase_messaging: ^15.2.6

  # Notificaciones locales
  flutter_local_notifications: ^17.2.1

  # Localización y mapas
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  # Autenticación
  google_sign_in: ^6.1.6
  crypto: ^3.0.3
  # UI y Navigation
  provider: ^6.1.1
  go_router: ^15.1.2

  # Funcionalidades principales
  camera: ^0.11.1
  image_picker: ^1.0.4
  google_maps_flutter: ^2.5.0
  qr_flutter: ^4.1.0
  qr_code_scanner_plus: ^2.0.10+1

  # IA y ML
  tflite_flutter: ^0.11.0
  image: ^4.1.3

  # Utilidades
  cached_network_image: ^3.3.0
  uuid: ^4.2.1
  intl: ^0.20.2
  permission_handler: ^12.0.0+1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5


  # Math para cálculos de similitud
  vector_math: ^2.1.4

  # Para selección de imágenes desde galería
  file_picker: ^6.1.1


  # Para análisis de metadatos de imagen
  exif: ^3.3.0

  # Para compresión de imágenes
  flutter_image_compress: ^2.1.0

  # Para mostrar progreso de análisis
  percent_indicator: ^4.2.3

  # Para animaciones suaves
  animations: ^2.0.8


dependency_overrides:
  google_sign_in_ios: ^5.6.0
  google_sign_in_platform_interface: ^2.3.0
  file_picker:
    git:
      url: https://github.com/miguelpruivo/flutter_file_picker.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1  # Agregar esta línea

# Configuración del ícono de la app
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21

  # Para Android adaptive icons
  adaptive_icon_background: "#4A7AA7"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"

  # Configuraciones específicas
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/models/
    - assets/icons/
    - assets/ai/
