name: apppetid
description: "Red social inteligente para mascotas y sus dueños."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase - Últimas versiones
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  firebase_messaging: ^15.2.6

  # Autenticación
  google_sign_in: ^6.0.2

  # UI y Navigation
  provider: ^6.1.1
  go_router: ^15.1.2

  # Funcionalidades principales
  camera: ^0.11.1
  image_picker: ^1.0.4
  geolocator: ^14.0.1
  google_maps_flutter: ^2.5.0
  qr_flutter: ^4.1.0
  qr_code_scanner_plus: ^2.0.10+1

  # IA y ML
  tflite_flutter: ^0.11.0
  image: ^4.1.3

  # Utilidades
  cached_network_image: ^3.3.0
  uuid: ^4.2.1
  intl: ^0.20.2
  permission_handler: ^12.0.0+1
  shared_preferences: ^2.2.2

dependency_overrides:
  google_sign_in_ios: ^5.6.0
  google_sign_in_platform_interface: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/models/
    - assets/icons/
